webside: "笑颜网"

# Header
root: "https://github.com/objchris/hexo-theme-bookcase"

# The tag you want to show when user enter you website
indicate: "home"

# use search function
search: true

home: "home"
